# -*- coding: utf-8 -*-
"""
一键发版脚本

将 bump版本 → 打包 → git commit/tag → 创建GitHub Release → 上传zip → 更新Gist
全部自动化，运行一条命令即可完成发版。

用法：
    python tools/release.py patch     # 补丁版本 1.0.2 → 1.0.3
    python tools/release.py minor     # 次版本   1.0.2 → 1.1.0
    python tools/release.py major     # 主版本   1.0.2 → 2.0.0

前置条件（仅首次需要）：
    1. 在项目根目录创建 .env 文件，写入：
       GITHUB_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    2. Token 需要 repo + gist 权限
       获取地址：https://github.com/settings/tokens/new
       勾选：repo (Full control) 和 gist
"""

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.request
import urllib.error
import urllib.parse
from datetime import date


def _configure_stdio():
    """Avoid crashing on consoles that cannot encode some Unicode symbols."""
    for stream_name in ("stdout", "stderr"):
        stream = getattr(sys, stream_name, None)
        if stream is None or not hasattr(stream, "reconfigure"):
            continue
        try:
            stream.reconfigure(errors="replace")
        except Exception:
            pass


_configure_stdio()

# ============================================================
# 路径与配置
# ============================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, PROJECT_ROOT)

from version import APP_NAME_EN
from repo_config import (
    GITHUB_OWNER, GITHUB_REPO, GIST_ID, GIST_ID_TEST, DOWNLOAD_PROXIES,
)


def _proxied_url(url: str) -> str:
    """给 GitHub 下载 URL 加上第一个可用的代理前缀，加速国内下载"""
    if not url or not url.startswith("https://github.com/"):
        return url
    for prefix in DOWNLOAD_PROXIES:
        if prefix:  # 跳过空字符串（直连兜底）
            return prefix + url
    return url


def _load_env() -> dict:
    """从 .env 文件加载环境变量"""
    env_file = os.path.join(PROJECT_ROOT, ".env")
    env = {}
    if os.path.exists(env_file):
        with open(env_file, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    return env


def _get_token() -> str:
    """获取 GitHub Token"""
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        token = _load_env().get("GITHUB_TOKEN", "")
    if not token:
        print("[错误] 未找到 GITHUB_TOKEN")
        sys.exit(1)
    return token


def _current_branch() -> str:
    """获取当前分支名。"""
    branch = subprocess.run(
        "git rev-parse --abbrev-ref HEAD",
        cwd=PROJECT_ROOT, shell=True, capture_output=True, text=True
    ).stdout.strip()
    return branch or "master"


def _has_staged_changes() -> bool:
    """判断 git 暂存区是否有变更。"""
    result = subprocess.run(
        "git diff --cached --quiet",
        cwd=PROJECT_ROOT,
        shell=True
    )
    return result.returncode != 0


_VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")


def _version_key(v: str) -> tuple:
    m = _VERSION_RE.match((v or "").strip())
    if not m:
        return (0, 0, 0)
    return tuple(int(x) for x in m.groups())


def _load_universal_patch(dist_dir: str, version: str) -> dict:
    """Load universal patch asset generated by build.py.

    Returns:
        dict with keys: file_path, min_version, size_mb
        or empty dict if no patch found.
    """
    patch_info_file = os.path.join(dist_dir, "patch-info.json")

    if os.path.exists(patch_info_file):
        try:
            with open(patch_info_file, "r", encoding="utf-8") as f:
                patch_info = json.load(f)
            patch_name = patch_info.get("patch_name", "")
            min_version = patch_info.get("min_version", "")
            if patch_name:
                path = os.path.join(dist_dir, patch_name)
                if os.path.exists(path):
                    return {
                        "file_path": path,
                        "min_version": min_version,
                        "size_mb": round(os.path.getsize(path) / (1024 * 1024), 2),
                    }
        except Exception as e:
            print(f"  [patch] 解析 patch-info.json 失败: {e}")

    # 兼容：直接查找命名约定的补丁文件
    fallback = os.path.join(dist_dir, f"{APP_NAME_EN}-V{version}-patch.zip")
    if os.path.exists(fallback):
        return {
            "file_path": fallback,
            "min_version": "",
            "size_mb": round(os.path.getsize(fallback) / (1024 * 1024), 2),
        }

    return {}


# ============================================================
# GitHub API 封装
# ============================================================
def _github_api(method: str, url: str, token: str,
                data: dict = None, raw_body: bytes = None,
                content_type: str = "application/json") -> dict:
    """通用 GitHub API 请求"""
    body = None
    if data is not None:
        body = json.dumps(data).encode("utf-8")
    elif raw_body is not None:
        body = raw_body

    req = urllib.request.Request(url, data=body, method=method)
    req.add_header("Authorization", f"token {token}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", APP_NAME_EN)
    if body is not None:
        req.add_header("Content-Type", content_type)

    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            resp_body = resp.read().decode("utf-8")
            return json.loads(resp_body) if resp_body else {}
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="replace")
        print(f"  [API 错误] {e.code}: {err_body[:500]}")
        raise


def _upload_release_asset(upload_url: str, file_path: str, token: str):
    """上传 Release 附件（curl 流式上传，不把文件载入内存）"""
    filename = os.path.basename(file_path)
    size_mb = os.path.getsize(file_path) / (1024 * 1024)

    # upload_url 模板形如 https://uploads.github.com/repos/.../releases/123/assets{?name,label}
    base_url = upload_url.split("{")[0]
    url = f"{base_url}?name={urllib.parse.quote(filename)}"

    print(f"  上传: {filename} ({size_mb:.1f} MB)")

    curl = r"C:\Windows\System32\curl.exe"
    cmd = [
        curl, "-#",
        "-X", "POST",
        "-H", f"Authorization: token {token}",
        "-H", "Accept: application/vnd.github+json",
        "-H", "Content-Type: application/zip",
        "--data-binary", f"@{file_path}",
        "-o", "-",
        url,
    ]

    result = subprocess.run(cmd, stdout=subprocess.PIPE)
    if result.returncode != 0:
        print(f"[ERROR] [上传失败] curl 退出码 {result.returncode}")
        raise RuntimeError(f"curl upload failed: exit {result.returncode}")

    resp = json.loads(result.stdout.decode("utf-8", errors="replace"))
    if "browser_download_url" not in resp:
        print(f"[ERROR] [上传失败] 响应: {str(resp)[:300]}")
        raise RuntimeError(f"upload response missing browser_download_url: {resp}")

    print("  [OK]")
    return resp["browser_download_url"]


# ============================================================
# 发版步骤
# ============================================================
def step_bump_version(level: str) -> str:
    """步骤1：递增版本号"""
    from version import APP_VERSION as old_ver
    # 调用 build.py 中的 bump 逻辑
    from build import bump_version
    new_ver = bump_version(level)
    return new_ver


def step_get_current_version() -> str:
    """读取当前 version.py 中的版本号（不递增）。"""
    import importlib
    import version as _ver_mod
    importlib.reload(_ver_mod)
    return _ver_mod.APP_VERSION


def step_build() -> dict:
    """步骤2：打包"""
    print(f"\n{'='*60}")
    print(f"  [步骤 2/6] 打包...")
    print(f"{'='*60}\n")

    result = subprocess.run(
        [sys.executable, os.path.join(SCRIPT_DIR, "build.py")],
        cwd=PROJECT_ROOT,
    )
    if result.returncode != 0:
        print("[错误] 打包失败")
        sys.exit(1)

    # 找到产物文件（必须 reload，因为 bump_version 已修改 version.py，
    # 但 Python 模块缓存仍持有旧值）
    import importlib
    import version as _ver_mod
    importlib.reload(_ver_mod)
    APP_VERSION = _ver_mod.APP_VERSION
    dist_dir = os.path.join(PROJECT_ROOT, "dist")
    full_zip = os.path.join(dist_dir, f"{APP_NAME_EN}-V{APP_VERSION}.zip")

    if not os.path.exists(full_zip):
        print(f"[错误] 找不到全量包: {full_zip}")
        sys.exit(1)

    assets = {"full_zip": full_zip}
    patch_info = _load_universal_patch(dist_dir, APP_VERSION)
    if patch_info and patch_info.get("file_path"):
        assets["patch_zip"] = patch_info["file_path"]
        assets["patch_min_version"] = patch_info.get("min_version", "")
        assets["patch_size_mb"] = patch_info.get("size_mb", 0)
        min_ver = patch_info.get("min_version") or "?"
        print(f"  [patch] 通用补丁包: {os.path.basename(patch_info['file_path'])}")
        print(f"  [patch] 覆盖范围: V{min_ver}+ -> V{APP_VERSION} ({patch_info['size_mb']:.2f} MB)")

    return assets


def step_git_commit_and_tag(tag_name: str, branch: str, commit_message: str):
    """步骤3：git commit + tag"""
    print(f"\n{'='*60}")
    print(f"  [步骤 3/6] Git commit + tag {tag_name}")
    print(f"{'='*60}\n")

    def _run(cmd):
        print(f"  $ {cmd}")
        subprocess.run(cmd, cwd=PROJECT_ROOT, shell=True, check=True)

    _run("git add -A")
    if _has_staged_changes():
        safe_msg = commit_message.replace('"', "'")
        _run(f'git commit -m "{safe_msg}"')
    else:
        print("  [提示] 当前无可提交变更，跳过 commit。")

    tag_exists = subprocess.run(
        f"git rev-parse -q --verify refs/tags/{tag_name}",
        cwd=PROJECT_ROOT, shell=True,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    ).returncode == 0
    if tag_exists:
        print(f"[错误] 标签已存在：{tag_name}")
        sys.exit(1)

    _run(f"git tag {tag_name}")
    _run(f"git push origin {branch}")
    _run(f"git push origin {tag_name}")


def step_create_release(tag_name: str, release_name: str, token: str, changelog: str,
                        prerelease: bool = False) -> dict:
    """步骤4：创建 GitHub Release"""
    print(f"\n{'='*60}")
    release_type = "Pre-release" if prerelease else "正式 Release"
    print(f"  [步骤 4/6] 创建 GitHub {release_type} {tag_name}")
    print(f"{'='*60}\n")

    url = f"https://api.github.com/repos/{GITHUB_OWNER}/{GITHUB_REPO}/releases"
    data = {
        "tag_name": tag_name,
        "name": release_name,
        "body": changelog or f"{release_name} 版本发布",
        "draft": False,
        "prerelease": bool(prerelease),
    }

    release = _github_api("POST", url, token, data=data)
    print(f"  Release 创建成功: {release.get('html_url', '')}")
    return release


def step_upload_assets(release: dict, assets: dict, token: str) -> dict:
    """步骤5：上传 zip 附件（全量包 + 通用补丁包）"""
    print(f"\n{'='*60}")
    print(f"  [步骤 5/6] 上传发布包到 GitHub...")
    print(f"{'='*60}\n")

    upload_url = release.get("upload_url", "")
    urls = {}

    full_url = _upload_release_asset(upload_url, assets["full_zip"], token)
    urls["download_url"] = full_url

    if "patch_zip" in assets and os.path.exists(assets["patch_zip"]):
        patch_url = _upload_release_asset(upload_url, assets["patch_zip"], token)
        urls["patch_url"] = patch_url

    return urls


def step_update_gist(version: str, urls: dict, assets: dict,
                     token: str, changelog: str,
                     gist_id: str, gist_target: str = "prod",
                     prerelease: bool = False) -> dict:
    """步骤6：更新 GitHub Gist version.json"""
    print(f"\n{'='*60}")
    target_text = "测试通道" if gist_target == "test" else "正式通道"
    print(f"  [步骤 6/6] 更新 GitHub Gist version.json（{target_text}）")
    print(f"{'='*60}\n")

    full_size = os.path.getsize(assets["full_zip"]) / (1024 * 1024)

    version_data = {
        "latest_version": version,
        "download_url": _proxied_url(urls.get("download_url", "")),
        "download_url_direct": urls.get("download_url", ""),
        "changelog": changelog or f"V{version} 版本发布",
        "release_date": date.today().isoformat(),
        "min_version": "1.0.0",
        "file_size_mb": round(full_size, 1),
        "channel": "prerelease" if prerelease else "stable",
    }

    if "patch_url" in urls:
        version_data["patch_url"] = _proxied_url(urls["patch_url"])
        version_data["patch_url_direct"] = urls["patch_url"]
        version_data["patch_size_mb"] = assets.get("patch_size_mb", 0)
        version_data["min_patch_version"] = assets.get("patch_min_version", "")
        # 兼容旧客户端（V1.0.6-）：旧版 updater 用 patch_base_version 精确匹配
        version_data["patch_base_version"] = assets.get("patch_min_version", "")

    gist_url = f"https://api.github.com/gists/{gist_id}"
    data = {
        "files": {
            "version.json": {
                "content": json.dumps(version_data, ensure_ascii=False, indent=4)
            }
        }
    }

    _github_api("PATCH", gist_url, token, data=data)
    print(f"  Gist 更新成功! (target={gist_target}, gist={gist_id})")
    print(f"  内容: {json.dumps(version_data, ensure_ascii=False, indent=2)}")
    return version_data


# ============================================================
# 主流程
# ============================================================
def release(level: str, changelog: str = "",
            prerelease: bool = False,
            gist_target: str = "prod",
            no_bump: bool = False,
            tag_suffix: str = ""):
    token = _get_token()

    # 测试 token 是否有效
    print("验证 GitHub Token...", end=" ", flush=True)
    try:
        _github_api("GET", "https://api.github.com/user", token)
        print("OK")
    except Exception:
        print("FAIL")
        print("[错误] GitHub Token 无效或网络不通")
        sys.exit(1)
    print()

    branch = _current_branch()
    gist_target = (gist_target or "prod").strip().lower()
    if gist_target not in ("prod", "test"):
        print(f"[错误] --gist-target 仅支持 prod/test，收到: {gist_target}")
        sys.exit(1)
    if branch != "master" and not prerelease:
        print(f"[错误] 当前分支为 {branch}，非 master 分支禁止正式发布。")
        print("       请使用 --prerelease 进行预发布，或切换到 master。")
        sys.exit(1)
    if not prerelease and gist_target != "prod":
        print("[错误] 正式发布仅允许 --gist-target prod。")
        sys.exit(1)
    if prerelease and gist_target == "prod":
        print("[错误] 预发布禁止写入正式 Gist（prod）。请使用 --gist-target test。")
        sys.exit(1)
    if gist_target == "test" and not GIST_ID_TEST:
        print("[错误] 未配置 GIST_ID_TEST，无法写入测试更新通道。")
        print("       请先在 repo_config.py 中设置 GIST_ID_TEST。")
        sys.exit(1)

    print(f"{'='*60}")
    print("  发布上下文")
    print(f"{'='*60}")
    print(f"  branch      : {branch}")
    print(f"  prerelease  : {prerelease}")
    print(f"  gist_target : {gist_target}")
    print(f"  no_bump     : {no_bump}")
    print(f"{'='*60}\n")

    # 步骤 1：版本号
    print(f"{'='*60}")
    if no_bump:
        print("  [步骤 1/6] 跳过版本递增（--no-bump）")
        print(f"{'='*60}\n")
        new_ver = step_get_current_version()
        print(f"  当前版本: {new_ver}\n")
    else:
        print(f"  [步骤 1/6] 递增版本号 ({level})")
        print(f"{'='*60}\n")
        new_ver = step_bump_version(level)

    suffix = (tag_suffix or "").strip()
    if prerelease and not suffix:
        suffix = "beta"

    tag_name = f"v{new_ver}" + (f"-{suffix}" if suffix else "")
    release_name = f"V{new_ver}" + (f" ({suffix})" if suffix else "")
    commit_message = f"release: {tag_name}"

    # 步骤 2：打包
    assets = step_build()

    # 步骤 3：git
    step_git_commit_and_tag(tag_name, branch, commit_message)

    # 步骤 4：创建 GitHub Release
    release_obj = step_create_release(
        tag_name, release_name, token, changelog, prerelease=prerelease
    )

    # 步骤 5：上传附件到 GitHub
    urls = step_upload_assets(release_obj, assets, token)

    # 步骤 6：更新 GitHub Gist
    target_gist_id = GIST_ID if gist_target == "prod" else GIST_ID_TEST
    step_update_gist(
        new_ver, urls, assets, token, changelog,
        gist_id=target_gist_id,
        gist_target=gist_target,
        prerelease=prerelease
    )

    # 完成
    print(f"\n{'='*60}")
    release_type = "预发布" if prerelease else "正式发布"
    print(f"  {tag_name} {release_type}完成！")
    print(f"  - GitHub: 已发布")
    print(f"  - Gist通道: {gist_target}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="一键发版：bump → build → git → release → gist",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""示例：
  python tools/release.py patch                    # 1.0.2 → 1.0.3
  python tools/release.py minor                    # 1.0.2 → 1.1.0
  python tools/release.py patch -m "修复水面线bug"  # 带更新日志
  python tools/release.py patch --prerelease --gist-target test --no-bump \\
      --tag-suffix beta.20260307.1
""")
    parser.add_argument("level", choices=["patch", "minor", "major"],
                        help="版本递增级别（--no-bump 时仅作兼容占位）")
    parser.add_argument("-m", "--message", default="",
                        help="更新日志（用 \\n 分隔多条）")
    parser.add_argument("--prerelease", action="store_true",
                        help="发布为 GitHub 预发布（Pre-release）")
    parser.add_argument("--gist-target", choices=["prod", "test"], default="prod",
                        help="更新通道：prod=正式Gist，test=测试Gist")
    parser.add_argument("--no-bump", action="store_true",
                        help="不递增 version.py（适合预发布验证）")
    parser.add_argument("--tag-suffix", default="",
                        help="tag后缀，如 beta.20260307.1，生成 vX.Y.Z-<suffix>")

    args = parser.parse_args()
    release(
        args.level,
        args.message,
        prerelease=args.prerelease,
        gist_target=args.gist_target,
        no_bump=args.no_bump,
        tag_suffix=args.tag_suffix,
    )
